export const packages = [
  {
    packageName: "ar100",
    version: "0.1.0",
    distro: "humble",
    infoLink: "https://github.com/rishikesavanramesh/SWERVE-DRIVE",
    architecture: "amd64",
    downloadLink: "./../.././r2ppa/apt-repo/pool/main/binary-amd64/ros-humble-ar100_0.1.0-0jammy_amd64.deb",
  },
  {
    packageName: "ar100-bringup",
    version: "0.1.0",
    distro: "humble",
    infoLink: "https://github.com/rishikesavanramesh/SWERVE-DRIVE",
    architecture: "amd64",
    downloadLink: "./../.././r2ppa/apt-repo/pool/main/binary-amd64/ros-humble-ar100-bringup_0.1.0-0jammy_amd64.deb",
  },
  {
    packageName: "ar100-description",
    version: "0.1.0",
    distro: "humble",
    infoLink: "https://github.com/rishikesavanramesh/SWERVE-DRIVE",
    architecture: "amd64",
    downloadLink: "./../.././r2ppa/apt-repo/pool/main/binary-amd64/ros-humble-ar100-description_0.1.0-0jammy_amd64.deb",
  },
  {
    packageName: "ar100-gazebo",
    version: "0.1.0",
    distro: "humble",
    infoLink: "https://github.com/rishikesavanramesh/SWERVE-DRIVE",
    architecture: "amd64",
    downloadLink: "./../.././r2ppa/apt-repo/pool/main/binary-amd64/ros-humble-ar100-gazebo_0.1.0-0jammy_amd64.deb",
  },
  {
    packageName: "ar100-navigation",
    version: "0.1.0",
    distro: "humble",
    infoLink: "https://github.com/rishikesavanramesh/SWERVE-DRIVE",
    architecture: "amd64",
    downloadLink: "./../.././r2ppa/apt-repo/pool/main/binary-amd64/ros-humble-ar100-navigation_0.1.0-0jammy_amd64.deb",
  },
  {
    packageName: "ar100-slam",
    version: "0.1.0",
    distro: "humble",
    infoLink: "https://github.com/rishikesavanramesh/SWERVE-DRIVE",
    architecture: "amd64",
    downloadLink: "./../.././r2ppa/apt-repo/pool/main/binary-amd64/ros-humble-ar100-slam_0.1.0-0jammy_amd64.deb",
  },
  {
    packageName: "swerve-drive-core",
    version: "1.0.0",
    distro: "humble",
    infoLink: "https://github.com/rishikesavanramesh/SWERVE-DRIVE",
    architecture: "amd64",
    downloadLink: "./../.././r2ppa/apt-repo/pool/main/binary-amd64/ros-humble-swerve-drive-core_1.0.0-0jammy_amd64.deb",
  },
  {
    packageName: "swervebot-bringup",
    version: "0.0.0",
    distro: "humble",
    infoLink: "https://github.com/rishikesavanramesh/SWERVE-DRIVE",
    architecture: "amd64",
    downloadLink: "./../.././r2ppa/apt-repo/pool/main/binary-amd64/ros-humble-swervebot-bringup_0.0.0-0jammy_amd64.deb",
  },
  {
    packageName: "swervebot-description",
    version: "0.0.0",
    distro: "humble",
    infoLink: "https://github.com/rishikesavanramesh/SWERVE-DRIVE",
    architecture: "amd64",
    downloadLink: "./../.././r2ppa/apt-repo/pool/main/binary-amd64/ros-humble-swervebot-description_0.0.0-0jammy_amd64.deb",
  },
];
